 #开发环境配置 dev
 server: 
  port: 8080
 logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){yellow} %clr(%contextName [%thread]){green} %clr(%-5level){red} %clr(%logger{36} - %msg%n){blue}"
  file: app.log  
 mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  
 pagehelper:
  helper-dialect: sqlite
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
 
 redis:
        host: localhost
        port: 6379
        timeout: 20000
        #cluster:
        #    nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
        #    maxRedirects: 6
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
 
 spring:
  output:
    ansi:
      enabled: ALWAYS
  security:    
    user: 
      name: admin
      password: 123456         
  datasource:     
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/example.db
  profiles:
    active: dev